[2023-07-29T23:35:50.341+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: trainer.test manual__2023-07-29T22:26:04.728771+00:00 [queued]>
[2023-07-29T23:35:50.348+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: trainer.test manual__2023-07-29T22:26:04.728771+00:00 [queued]>
[2023-07-29T23:35:50.348+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-29T23:35:50.361+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): test> on 2023-07-29 22:26:04.728771+00:00
[2023-07-29T23:35:50.374+0000] {standard_task_runner.py:57} INFO - Started process 632842 to run task
[2023-07-29T23:35:50.376+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'trainer', 'test', 'manual__2023-07-29T22:26:04.728771+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/train_dag.py', '--cfg-path', '/tmp/tmp6r3srl4e']
[2023-07-29T23:35:50.376+0000] {standard_task_runner.py:85} INFO - Job 58: Subtask test
[2023-07-29T23:35:50.425+0000] {task_command.py:410} INFO - Running <TaskInstance: trainer.test manual__2023-07-29T22:26:04.728771+00:00 [running]> on host ip-172-31-37-30.ap-south-1.compute.internal
[2023-07-29T23:35:50.508+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='trainer' AIRFLOW_CTX_TASK_ID='test' AIRFLOW_CTX_EXECUTION_DATE='2023-07-29T22:26:04.728771+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-29T22:26:04.728771+00:00'
[2023-07-29T23:35:50.516+0000] {logging_mixin.py:150} WARNING - /home/ubuntu/theft-detection/env1/lib/python3.10/site-packages/torchvision/models/_utils.py:208 UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
[2023-07-29T23:35:50.517+0000] {logging_mixin.py:150} WARNING - /home/ubuntu/theft-detection/env1/lib/python3.10/site-packages/torchvision/models/_utils.py:223 UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=None`.
[2023-07-29T23:35:50.675+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/theft-detection/env1/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/ubuntu/theft-detection/env1/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/ubuntu/GenAI-Rush/GenAI-Rush-FedGen/airflow/dags/train_dag.py", line 93, in test_module
    testObj.testClientModels()
  File "/home/ubuntu/GenAI-Rush/GenAI-Rush-FedGen/fedgen/test.py", line 39, in testClientModels
    loaderObj = CreateLoaders(save_path=self.save_path, batch_size=self.batch_size, test_batch_size=self.max_physical_batch_size, worker=worker)
TypeError: CreateLoaders.__init__() got an unexpected keyword argument 'test_batch_size'
[2023-07-29T23:35:50.684+0000] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=trainer, task_id=test, execution_date=20230729T222604, start_date=20230729T233550, end_date=20230729T233550
[2023-07-29T23:35:50.692+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 58 for task test (CreateLoaders.__init__() got an unexpected keyword argument 'test_batch_size'; 632842)
[2023-07-29T23:35:50.748+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-29T23:35:50.774+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
